# @file       Makefile
# @brief      Brief description
# @author     Jozef Zuzelka <jozef.zuzelka@gmail.com>
# @date
#  - Created: 04.06.2020 15:43
#  - Edited:  04.06.2020 15:43
# @version    1.0.0
# @par        make: GNU Make 3.81
# @bug
# @todo


TARGET=test

CXX=g++
CXXFLAGS=-std=c++17 -pedantic -Wall -Wextra -g
LDFLAGS=
.PHONY: clean

#$(TARGET): $(TARGET).o
#	$(CXX) $(CXXFLAGS) -o $@ $< $(LDFLAGS)

#%: %.cpp
#	$(CXX) $(CXXFLAGS) -o $@ $< $(LDFLAGS)

all : $(TARGET)

clean:
	-rm $(TARGET) $(TARGET).o
